-- Base de datos para Sistema de Gestión Escolar Marcelino Champagnat
CREATE DATABASE IF NOT EXISTS colegio_champagnat CHARACTER SET utf8mb4 COLLATE utf8mb4_spanish_ci;
USE colegio_champagnat;

-- Tabla de cursos
CREATE TABLE cursos (
    id INT PRIMARY KEY AUTO_INCREMENT,
    grado VARCHAR(10) NOT NULL,
    seccion CHAR(1) NOT NULL,
    descripcion TEXT NULL,
    año_escolar VARCHAR(10) DEFAULT '2025',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabla de estudiantes con datos completos
CREATE TABLE estudiantes (
    id INT PRIMARY KEY AUTO_INCREMENT,
    numero INT NOT NULL,
    ci VARCHAR(20) UNIQUE NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    apellido_paterno VARCHAR(100) NOT NULL,
    apellido_materno VARCHAR(100) NULL,
    nombre_completo VARCHAR(300) NOT NULL,
    fecha_nacimiento DATE NULL,
    genero ENUM('masculino', 'femenino') NULL,
    direccion TEXT NULL,
    telefono VARCHAR(20) NULL,
    nombre_tutor VARCHAR(200) NULL,
    telefono_tutor VARCHAR(20) NULL,
    email_tutor VARCHAR(100) NULL,
    curso_id INT,
    estado ENUM('activo', 'inactivo') DEFAULT 'activo',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (curso_id) REFERENCES cursos(id)
);

-- Tabla de usuarios (para el login) - Versión simplificada
CREATE TABLE usuarios (
    id INT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insertar usuario administrador por defecto
INSERT INTO usuarios (username, password) VALUES 
('admin', '$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi'); -- password: password

-- Insertar cursos de ejemplo (solo algunos para empezar)
INSERT INTO cursos (grado, seccion, descripcion) VALUES
('1ro', 'A', 'Primer año de secundaria - Sección A'),
('1ro', 'B', 'Primer año de secundaria - Sección B'),
('2do', 'A', 'Segundo año de secundaria - Sección A'),
('2do', 'B', 'Segundo año de secundaria - Sección B');

-- Insertar estudiantes de 1ro A (basados en tu HTML)
INSERT INTO estudiantes (numero, ci, nombre, apellido_paterno, apellido_materno, nombre_completo, curso_id, estado) VALUES
(1, '12345001', 'MIA SHERASADE', 'ABAN', 'ABAN', 'ABAN ABAN MIA SHERASADE', 1, 'activo'),
(2, '12345002', 'SILVIA AYLIN', 'ACARAPI', 'ESCALERA', 'ACARAPI ESCALERA SILVIA AYLIN', 1, 'activo'),
(3, '12345003', 'RUTH STEFANY', 'AZURDUY', 'ANTONIO', 'AZURDUY ANTONIO RUTH STEFANY', 1, 'activo'),
(4, '12345004', 'NAIARA NOEMI', 'BAZAN', 'MARTINEZ', 'BAZAN MARTINEZ NAIARA NOEMI', 1, 'activo'),
(5, '12345005', 'DARLYN JHORLEY', 'CAMPOS', 'TACA', 'CAMPOS TACA DARLYN JHORLEY', 1, 'activo'),
(6, '12345006', 'BETZABETH', 'CARRILLO', 'CUELLAR', 'CARRILLO CUELLAR BETZABETH', 1, 'activo'),
(7, '12345007', 'YAREN ARELY', 'CASTELLON', 'CLAUDIO', 'CASTELLON CLAUDIO YAREN ARELY', 1, 'activo'),
(8, '12345008', 'JAVIERA', 'CHAMON', 'SALAS', 'CHAMON SALAS JAVIERA', 1, 'activo'),
(9, '12345009', 'OCTAVIO KAMIL', 'DE LA VIA', 'LUNA', 'DE LA VIA LUNA OCTAVIO KAMIL', 1, 'activo'),
(10, '12345010', 'EIMMY NICOLE', 'DELGADILLO', 'DIAZ', 'DELGADILLO DIAZ EIMMY NICOLE', 1, 'activo');

-- Insertar estudiantes de 1ro B
INSERT INTO estudiantes (numero, ci, nombre, apellido_paterno, apellido_materno, nombre_completo, curso_id, estado) VALUES
(1, '12345101', 'ROLY JOSUE', 'ABASTO', 'LEDEZMA', 'ABASTO LEDEZMA ROLY JOSUE', 2, 'activo'),
(2, '12345102', 'BRIANNA ADA', 'ATUNDUAGA', 'JALDIN', 'ATUNDUAGA JALDIN BRIANNA ADA', 2, 'activo'),
(3, '12345103', 'LUCIANA KATHERINE', 'BADILLO', 'BARRETO', 'BADILLO BARRETO LUCIANA KATHERINE', 2, 'activo'),
(4, '12345104', 'LUCAS', 'CABRERA', 'RAMOS', 'CABRERA RAMOS LUCAS', 2, 'activo'),
(5, '12345105', 'MARIANA', 'CALDERON', 'MORENO', 'CALDERON MORENO MARIANA', 2, 'activo'),
(6, '12345106', 'DIEGO ANDREY', 'CALLAHUARA', 'CHIPANA', 'CALLAHUARA CHIPANA DIEGO ANDREY', 2, 'activo'),
(7, '12345107', 'ISABELLA JULITH', 'CASTRO', 'BARBA', 'CASTRO BARBA ISABELLA JULITH', 2, 'activo'),
(8, '12345108', 'BENJAMIN', 'CEDEÑO', 'SOLIZ', 'CEDEÑO SOLIZ BENJAMIN', 2, 'activo'),
(9, '12345109', 'NAYHERLIN', 'CHIPANA', 'OLLISCO', 'CHIPANA OLLISCO NAYHERLIN', 2, 'activo'),
(10, '12345110', 'LUCA DANIEL', 'CHOQUE', 'MENGARI', 'CHOQUE MENGARI LUCA DANIEL', 2, 'activo'),
(11, '12345111', 'ROVIN ANDRES', 'EDGLEY', 'PEREDO', 'EDGLEY PEREDO ROVIN ANDRES', 2, 'activo'),
(12, '12345112', 'PAULA SOFIA', 'FERNANDEZ', 'SOLAR', 'FERNANDEZ SOLAR PAULA SOFIA', 2, 'activo'),
(13, '12345113', 'ROGER FARID', 'GONZALES', 'RAMIREZ', 'GONZALES RAMIREZ ROGER FARID', 2, 'activo'),
(14, '12345114', 'EDITH', 'GUARDIA', 'FLORES', 'GUARDIA FLORES EDITH', 2, 'activo'),
(15, '12345115', 'ALESSANDRA MARELY', 'LIMA', 'LEON', 'LIMA LEON ALESSANDRA MARELY', 2, 'activo'),
(16, '12345116', 'ESTEFANY FERNANDA', 'LINO', 'QUISPE', 'LINO QUISPE ESTEFANY FERNANDA', 2, 'activo'),
(17, '12345117', 'CHRISTIAN GABRIEL', 'LOPEZ', 'VARGAS', 'LOPEZ VARGAS CHRISTIAN GABRIEL', 2, 'activo'),
(18, '12345118', 'DYLAN ESTIVE', 'LUIZAGA', 'PANTOJA', 'LUIZAGA PANTOJA DYLAN ESTIVE', 2, 'activo'),
(19, '12345119', 'VANIA ANAHI', 'MAMANI', 'BARRETO', 'MAMANI BARRETO VANIA ANAHI', 2, 'activo'),
(20, '12345120', 'LUIS KAZUKI', 'MENDEZ', 'ARTEAGA', 'MENDEZ ARTEAGA LUIS KAZUKI', 2, 'activo'),
(21, '12345121', 'JOSE DAVID', 'MORON', 'AGUIRRE', 'MORON AGUIRRE JOSE DAVID', 2, 'activo'),
(22, '12345122', 'SEBASTIAN', 'NUÑEZ', 'MUÑOZ', 'NUÑEZ MUÑOZ SEBASTIAN', 2, 'activo'),
(23, '12345123', 'FERNANDA', 'ORDOÑEZ', 'GALARZA', 'ORDOÑEZ GALARZA FERNANDA', 2, 'activo'),
(24, '12345124', 'ANGEL JOAQUIN', 'ORELLANA', 'JALDIN', 'ORELLANA JALDIN ANGEL JOAQUIN', 2, 'activo'),
(25, '12345125', 'VALERIA', 'ORTIZ', 'LOZA', 'ORTIZ LOZA VALERIA', 2, 'activo'),
(26, '12345126', 'ANGEL IGNACIO', 'PADILLA', 'CUELLAR', 'PADILLA CUELLAR ANGEL IGNACIO', 2, 'activo'),
(27, '12345127', 'IVAN NICOLAS', 'PADILLA', 'FERNANDEZ', 'PADILLA FERNANDEZ IVAN NICOLAS', 2, 'activo'),
(28, '12345128', 'DORYS ANE', 'PEREIRA', 'FUENTES', 'PEREIRA FUENTES DORYS ANE', 2, 'activo'),
(29, '12345129', 'JUAN JOSE', 'PIEROLA', 'SAAVEDRA', 'PIEROLA SAAVEDRA JUAN JOSE', 2, 'activo'),
(30, '12345130', 'FABIO ANDRES', 'RAMIREZ', 'TELLEZ', 'RAMIREZ TELLEZ FABIO ANDRES', 2, 'activo'),
(31, '12345131', 'MAITE MARGARITA', 'RENTERIA', 'CHUMACERO', 'RENTERIA CHUMACERO MAITE MARGARITA', 2, 'activo'),
(32, '12345132', 'MATEO', 'RIVERO', 'RAMIREZ', 'RIVERO RAMIREZ MATEO', 2, 'activo'),
(33, '12345133', 'LESLY JHASSEL', 'RODAS', 'DURAN', 'RODAS DURAN LESLY JHASSEL', 2, 'activo'),
(34, '12345134', 'ROMINA MAYEL', 'ROJAS', 'ROSADO', 'ROJAS ROSADO ROMINA MAYEL', 2, 'activo'),
(35, '12345135', 'TEYLOR LIMBER', 'ROJAS', 'VARGAS', 'ROJAS VARGAS TEYLOR LIMBER', 2, 'activo'),
(36, '12345136', 'JOSE EDWARD', 'ROSADO', 'NAVARRO', 'ROSADO NAVARRO JOSE EDWARD', 2, 'activo'),
(37, '12345137', 'KENDRA', 'SERRUDO', 'CARBALLO', 'SERRUDO CARBALLO KENDRA', 2, 'activo'),
(38, '12345138', 'VALENTINA JHAZMIN', 'SILES', 'GUTIERREZ', 'SILES GUTIERREZ VALENTINA JHAZMIN', 2, 'activo'),
(39, '12345139', 'BRENDA', 'SOLANO', 'MELENDRES', 'SOLANO MELENDRES BRENDA', 2, 'activo'),
(40, '12345140', 'ALICIA', 'VALVERDE', 'SEGOVIA', 'VALVERDE SEGOVIA ALICIA', 2, 'activo'),
(41, '12345141', 'ANJHALI JUDITH', 'VARGAS', 'PADILLA', 'VARGAS PADILLA ANJHALI JUDITH', 2, 'activo'),
(42, '12345142', 'SANTIAGO', 'ZAPATA', 'CRUZ', 'ZAPATA CRUZ SANTIAGO', 2, 'activo');

-- Insertar estudiantes de 2do A
INSERT INTO estudiantes (numero, ci, nombre, apellido_paterno, apellido_materno, nombre_completo, curso_id, estado) VALUES
(1, '12345201', 'OLIVIA', 'ALA', 'JALDIN', 'ALA JALDIN OLIVIA', 3, 'activo'),
(2, '12345202', 'DIOGO MATEO', 'ALEJO', 'VILLARPANDO', 'ALEJO VILLARPANDO DIOGO MATEO', 3, 'activo'),
(3, '12345203', 'ANGEL GUSTAVO', 'ALMANZA', 'PARADA', 'ALMANZA PARADA ANGEL GUSTAVO', 3, 'activo'),
(4, '12345204', 'ADABEL NICOL', 'ARECO', 'RODRIGUEZ', 'ARECO RODRIGUEZ ADABEL NICOL', 3, 'activo'),
(5, '12345205', 'PIERRE SANTIAGO', 'AYALA', 'SOLETO', 'AYALA SOLETO PIERRE SANTIAGO', 3, 'activo'),
(6, '12345206', 'KENDRA AYRIN', 'BRAVO', 'ESTEVEZ', 'BRAVO ESTEVEZ KENDRA AYRIN', 3, 'activo'),
(7, '12345207', 'CIELO ALEJANDRA', 'BUSTOS', 'GUTIERREZ', 'BUSTOS GUTIERREZ CIELO ALEJANDRA', 3, 'activo'),
(8, '12345208', 'THAIS GUADALUPE', 'CABALLERO', 'POÑE', 'CABALLERO POÑE THAIS GUADALUPE', 3, 'activo'),
(9, '12345209', 'MATEO LEONEL', 'CALLEJAS', 'ROJAS', 'CALLEJAS ROJAS MATEO LEONEL', 3, 'activo'),
(10, '12345210', 'LUCAS RICARDO', 'CARRY', 'EGUEZ', 'CARRY EGUEZ LUCAS RICARDO', 3, 'activo'),
(11, '12345211', 'MAYA ARLENE', 'CASTELLON', 'CLAUDIO', 'CASTELLON CLAUDIO MAYA ARLENE', 3, 'activo'),
(12, '12345212', 'BIANCA DAVINIA', 'CASTRO', 'PINTO', 'CASTRO PINTO BIANCA DAVINIA', 3, 'activo'),
(13, '12345213', 'JAVIER', 'CHAVEZ', 'BALDIVIEZO', 'CHAVEZ BALDIVIEZO JAVIER', 3, 'activo'),
(14, '12345214', 'NICOLAS', 'CHAVEZ', 'LUCAS', 'CHAVEZ LUCAS NICOLAS', 3, 'activo'),
(15, '12345215', 'LEANDRO FABRICIO', 'FERNANDEZ', 'PEREZ', 'FERNANDEZ PEREZ LEANDRO FABRICIO', 3, 'activo'),
(16, '12345216', 'LORNA MARIANA', 'GARRON', 'VILLARROEL', 'GARRON VILLARROEL LORNA MARIANA', 3, 'activo'),
(17, '12345217', 'LUIS ANTONIO', 'GONGORA', 'ARNEZ', 'GONGORA ARNEZ LUIS ANTONIO', 3, 'activo'),
(18, '12345218', 'GABRIEL', 'GUEVARA', 'MONTAÑO', 'GUEVARA MONTAÑO GABRIEL', 3, 'activo'),
(19, '12345219', 'FEDERICO GAEL', 'GUTIERREZ', 'ARNEZ', 'GUTIERREZ ARNEZ FEDERICO GAEL', 3, 'activo'),
(20, '12345220', 'DAVINIA', 'HINO', 'VILLAGOMEZ', 'HINO VILLAGOMEZ DAVINIA', 3, 'activo'),
(21, '12345221', 'NATALIA', 'HURTADO', 'PONCE', 'HURTADO PONCE NATALIA', 3, 'activo'),
(22, '12345222', 'JHIOMARA', 'JIMENEZ', 'PEREZ', 'JIMENEZ PEREZ JHIOMARA', 3, 'activo'),
(23, '12345223', 'CARLA ANDREA', 'LOAYZA', 'PINTO', 'LOAYZA PINTO CARLA ANDREA', 3, 'activo'),
(24, '12345224', 'CARLA ANDREA', 'LOAYZA', 'PINTO', 'LOAYZA PINTO CARLA ANDREA', 3, 'activo'),
(25, '12345225', 'MIA DANIELA', 'MENDEZ', 'CAMPOS', 'MENDEZ CAMPOS MIA DANIELA', 3, 'activo'),
(26, '12345226', 'AMED HIROSHI', 'OKAYASU', 'GALARZA', 'OKAYASU GALARZA AMED HIROSHI', 3, 'activo'),
(27, '12345227', 'FABIANA', 'PITTARY', 'MENDOZA', 'PITTARY MENDOZA FABIANA', 3, 'activo'),
(28, '12345228', 'SOFIA', 'PORCEL', 'MONTERO', 'PORCEL MONTERO SOFIA', 3, 'activo'),
(29, '12345229', 'KAMILA RAICEL', 'RAMIREZ', 'VAQUIATA', 'RAMIREZ VAQUIATA KAMILA RAICEL', 3, 'activo'),
(30, '12345230', 'CELESTE RAFAELA', 'REYNA', 'MENDIETA', 'REYNA MENDIETA CELESTE RAFAELA', 3, 'activo'),
(31, '12345231', 'BRAYAN', 'ROCHA', 'HERNANDEZ', 'ROCHA HERNANDEZ BRAYAN', 3, 'activo'),
(32, '12345232', 'ALISSON', 'ROCHA', 'ORTIZ', 'ROCHA ORTIZ ALISSON', 3, 'activo'),
(33, '12345233', 'YUSARA SAHIÑA', 'ROJAS', 'FERNANDEZ', 'ROJAS FERNANDEZ YUSARA SAHIÑA', 3, 'activo'),
(34, '12345234', 'MARIAN NAYARA', 'ROJAS', 'GARCIA', 'ROJAS GARCIA MARIAN NAYARA', 3, 'activo'),
(35, '12345235', 'SEBASTIAN', 'SAUCEDO', 'GOMEZ', 'SAUCEDO GOMEZ SEBASTIAN', 3, 'activo'),
(36, '12345236', 'NEDILJKA SOLANGE', 'SITIC', 'GARNICA', 'SITIC GARNICA NEDILJKA SOLANGE', 3, 'activo'),
(37, '12345237', 'YUVINKA', 'SOLARES', 'ROJAS', 'SOLARES ROJAS YUVINKA', 3, 'activo'),
(38, '12345238', 'CAMILA', 'TERCEROS', 'PEREZ', 'TERCEROS PEREZ CAMILA', 3, 'activo'),
(39, '12345239', 'CARLO MATHIAS', 'TUPA', 'PEDRAZA', 'TUPA PEDRAZA CARLO MATHIAS', 3, 'activo'),
(40, '12345240', 'BAUTISTA SANTIAGO', 'VACA', 'PEREZ', 'VACA PEREZ BAUTISTA SANTIAGO', 3, 'activo'),
(41, '12345241', 'MASAI FABRICIO', 'VERDE', 'RAMO', 'VERDE RAMO MASAI FABRICIO', 3, 'activo'),
(42, '12345242', 'ESTENTOR', 'VILLCA', 'COSTAS', 'VILLCA COSTAS ESTENTOR', 3, 'activo');

-- Insertar estudiantes de 2do B
INSERT INTO estudiantes (numero, ci, nombre, apellido_paterno, apellido_materno, nombre_completo, curso_id, estado) VALUES
(1, '12345301', 'FACUNDO ANDRE', 'ALBORNOS', 'MILLARES', 'ALBORNOS MILLARES FACUNDO ANDRE', 4, 'activo'),
(2, '12345302', 'NICOLAS', 'AZEÑAS', 'SOLIZ', 'AZEÑAS SOLIZ NICOLAS', 4, 'activo'),
(3, '12345303', 'YHAJAIRA NICOL', 'CACERES', 'PEREIRA', 'CACERES PEREIRA YHAJAIRA NICOL', 4, 'activo'),
(4, '12345304', 'LUCIANO JAVIER', 'CRISTALDO', 'CEDEÑO', 'CRISTALDO CEDEÑO LUCIANO JAVIER', 4, 'activo'),
(5, '12345305', 'YHOSMEIDA KATERYN', 'GALVEZ', 'ARIAS', 'GALVEZ ARIAS YHOSMEIDA KATERYN', 4, 'activo'),
(6, '12345306', 'SANTIAGO ANDRE', 'GONZALES', 'PELAEZ', 'GONZALES PELAEZ SANTIAGO ANDRE', 4, 'activo'),
(7, '12345307', 'REIXHELL', 'GONZALES', 'VALENCIA', 'GONZALES VALENCIA REIXHELL', 4, 'activo'),
(8, '12345308', 'GESU CARLOS', 'GUARDIA', 'ARCE', 'GUARDIA ARCE GESU CARLOS', 4, 'activo'),
(9, '12345309', 'YADIRA', 'HUANACOTA', 'ALVAREZ', 'HUANACOTA ALVAREZ YADIRA', 4, 'activo'),
(10, '12345310', 'MAUREN', 'JUSTINIANO', 'ZABALA', 'JUSTINIANO ZABALA MAUREN', 4, 'activo'),
(11, '12345311', 'DIANA VICTORIA', 'LOBOS', 'VEGA', 'LOBOS VEGA DIANA VICTORIA', 4, 'activo'),
(12, '12345312', 'LUCAS CHRISTOPHER', 'LUJO', 'RODRIGUEZ', 'LUJO RODRIGUEZ LUCAS CHRISTOPHER', 4, 'activo'),
(13, '12345313', 'ANIEL', 'MALDONADO', 'SALDAÑA', 'MALDONADO SALDAÑA ANIEL', 4, 'activo'),
(14, '12345314', 'IVANNA LUZ', 'MAMANI', 'LAURA', 'MAMANI LAURA IVANNA LUZ', 4, 'activo'),
(15, '12345315', 'NOVALY', 'MARTINEZ', 'ESCOBAR', 'MARTINEZ ESCOBAR NOVALY', 4, 'activo'),
(16, '12345316', 'SEBASTIAN', 'MEDRANO', 'CLAURE', 'MEDRANO CLAURE SEBASTIAN', 4, 'activo'),
(17, '12345317', 'SHAILA TALID', 'MELGAR', 'RODRIGUEZ', 'MELGAR RODRIGUEZ SHAILA TALID', 4, 'activo'),
(18, '12345318', 'LAURENT', 'MENACHO', 'PACHECO', 'MENACHO PACHECO LAURENT', 4, 'activo'),
(19, '12345319', 'NICOLAS', 'MERUBIA', 'ALTAMIRANO', 'MERUBIA ALTAMIRANO NICOLAS', 4, 'activo'),
(20, '12345320', 'LUCAS JEREMY', 'MIRABAL', 'MELENDRES', 'MIRABAL MELENDRES LUCAS JEREMY', 4, 'activo'),
(21, '12345321', 'DANNA NELIDA', 'NAVA', 'CHAMBI', 'NAVA CHAMBI DANNA NELIDA', 4, 'activo'),
(22, '12345322', 'YARITZA PAOLA', 'NEGRETTY', 'BARRERO', 'NEGRETTY BARRERO YARITZA PAOLA', 4, 'activo'),
(23, '12345323', 'KRISTHA ISABELLA', 'PALACIOS', 'OLIVERA', 'PALACIOS OLIVERA KRISTHA ISABELLA', 4, 'activo'),
(24, '12345324', 'KARLA JUDITH', 'PEÑA', 'AGUADO', 'PEÑA AGUADO KARLA JUDITH', 4, 'activo'),
(25, '12345325', 'ALBERT JOAO', 'PEREZ', 'TORRICO', 'PEREZ TORRICO ALBERT JOAO', 4, 'activo'),
(26, '12345326', 'GAEL BENITO', 'PINTO', 'AREVALO', 'PINTO AREVALO GAEL BENITO', 4, 'activo'),
(27, '12345327', 'VICTORIA SARIHT', 'QUIROZ', 'ORTIZ', 'QUIROZ ORTIZ VICTORIA SARIHT', 4, 'activo'),
(28, '12345328', 'LORENA RAQUEL', 'RAMIREZ', 'QUISPE', 'RAMIREZ QUISPE LORENA RAQUEL', 4, 'activo'),
(29, '12345329', 'CAMILA', 'RIVERO', 'RAMIREZ', 'RIVERO RAMIREZ CAMILA', 4, 'activo'),
(30, '12345330', 'KEVIN', 'ROCA', 'ALVIS', 'ROCA ALVIS KEVIN', 4, 'activo'),
(31, '12345331', 'OCTAVIO ANDRES', 'RODRIGUEZ', 'COCA', 'RODRIGUEZ COCA OCTAVIO ANDRES', 4, 'activo'),
(32, '12345332', 'JHOEL FARID', 'RODRIGUEZ', 'MENACHO', 'RODRIGUEZ MENACHO JHOEL FARID', 4, 'activo'),
(33, '12345333', 'DANIEL', 'ROJAS', 'MEJIA', 'ROJAS MEJIA DANIEL', 4, 'activo'),
(34, '12345334', 'KARELYS AILYN', 'ROJAS', 'VASQUEZ', 'ROJAS VASQUEZ KARELYS AILYN', 4, 'activo'),
(35, '12345335', 'JOSE ANDRES', 'ROMERO', 'FERRUFINO', 'ROMERO FERRUFINO JOSE ANDRES', 4, 'activo'),
(36, '12345336', 'ARIANA DAYNETH', 'VALENCIA', 'CAYO', 'VALENCIA CAYO ARIANA DAYNETH', 4, 'activo'),
(37, '12345337', 'LUANA BELEN', 'VALLEJOS', 'FLORES', 'VALLEJOS FLORES LUANA BELEN', 4, 'activo'),
(38, '12345338', 'ADRIAN', 'VARGAS', 'VARGAS', 'VARGAS VARGAS ADRIAN', 4, 'activo'),
(39, '12345339', 'DAVINIA FERNANDA', 'YARHUI', 'BALDERRAMA', 'YARHUI BALDERRAMA DAVINIA FERNANDA', 4, 'activo'),
(40, '12345340', 'ROSSE DANIELA', 'YARHUI', 'SANDOVAL', 'YARHUI SANDOVAL ROSSE DANIELA', 4, 'activo');
